var size = [38,40,42,42,44,46];
console.log(size);
console.log(typeof(size));
console.log(size[0]);
console.log(size[1]);
console.log(size[2]);
console.log(size[3]);
console.log(size[4]);
console.log(size[5]);
console.log(size[6]);